#=============================================
#   Cấu hình server
#=============================================
server:
  port: 18696
  servlet:
    context-path: /api
  #    cấu hình số luồng của server
  tomcat:
    threads:
      max: 50
#=============================================
#   SPRING CONFIG
#=============================================
spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/one_vote"
    username: "root"
    password: "123456"
    hikari:
      maximum-pool-size: 2
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: false
  main:
    banner-mode: off
  jersey:
    servlet:
      load-on-startup: 1
  mvc:
    format:
      date: dd/MM/yyyy HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
# cấu hình log
logging:
# đường dẫn cấu hình log
  config: ./src/main/resources/logback.xml
  level:
    org:
#      log thông tin cache khi sử dung anotaiton @Cacheable của String
      springframework:
        cache: trace
#=============================================
#   URL CONFIG
#=============================================
url-notify-service: http://localhost:18697/api/notifications
url-file-service: https://daihoi.vnubw.xtel.vn/api/files/upload
#=============================================
#   MAIL CONFIG
#=============================================
mailServer:
  host: smtp.gmail.com
  port: 587
  email: chuhuunam2000@gmail.com
  password: rtczgqpiyjszjjsx
  protocol: smtp
  isSSL: false